apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: my_namespace
spec:
  template:
    spec:
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
        command:
          - "/cloud_sql_proxy"
          - "-enable_iam_login"
          - "-log_debug_stdout"
          - "-ip_address_types=PRIVATE"
          - "-instances=trivy sample:europe-west1:sample=tcp:5432"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "500Mi"
            cpu: "20m"
          limits:
            memory: "700Mi"
            cpu: "500m"